/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package friendgameworking.charactercreator;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

/**
 *
 * @author julian
 */
public class CharacterCreatorUI extends javax.swing.JFrame {

    /**
     * Creates new form CharacterCreatorUI
     */
    public CharacterCreatorUI() throws IOException {
        initComponents();

        updateCharacter();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clothesMinus = new javax.swing.JButton();
        eyebrowsMinus = new javax.swing.JButton();
        eyesMinus = new javax.swing.JButton();
        hairMinus = new javax.swing.JButton();
        hatsMinus = new javax.swing.JButton();
        mouthsMinus = new javax.swing.JButton();
        otherBottomMinus = new javax.swing.JButton();
        otherTopMinus = new javax.swing.JButton();
        skinMinus = new javax.swing.JButton();
        nosesMinus = new javax.swing.JButton();
        clothesPlus = new javax.swing.JButton();
        eyebrowsPlus = new javax.swing.JButton();
        eyesPlus = new javax.swing.JButton();
        hairPlus = new javax.swing.JButton();
        hatsPlus = new javax.swing.JButton();
        mouthsPlus = new javax.swing.JButton();
        otherBottomPlus = new javax.swing.JButton();
        otherTopPlus = new javax.swing.JButton();
        skinPlus = new javax.swing.JButton();
        nosesPlus = new javax.swing.JButton();
        clothesText = new javax.swing.JLabel();
        eyebrowsText = new javax.swing.JLabel();
        eyesText = new javax.swing.JLabel();
        hairText = new javax.swing.JLabel();
        hatsText = new javax.swing.JLabel();
        mouthsText = new javax.swing.JLabel();
        nosesText = new javax.swing.JLabel();
        otherBottomText = new javax.swing.JLabel();
        otherTopText = new javax.swing.JLabel();
        skinText = new javax.swing.JLabel();
        hairColorButton = new javax.swing.JButton();
        eyebrowsColorButton = new javax.swing.JButton();
        clothesColorButton = new javax.swing.JButton();
        characterLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        colorComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        birthMonthComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        personalitySliderIE = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        personalitySliderIS = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        personalitySliderFT = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        personalitySliderPJ = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        personalityLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Character Creator");

        jButton1.setText("Generate!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Appearance"));
        jPanel3.setToolTipText("");

        clothesMinus.setText("-");
        clothesMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesMinusActionPerformed(evt);
            }
        });

        eyebrowsMinus.setText("-");
        eyebrowsMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyebrowsMinusActionPerformed(evt);
            }
        });

        eyesMinus.setText("-");
        eyesMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyesMinusActionPerformed(evt);
            }
        });

        hairMinus.setText("-");
        hairMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairMinusActionPerformed(evt);
            }
        });

        hatsMinus.setText("-");
        hatsMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatsMinusActionPerformed(evt);
            }
        });

        mouthsMinus.setText("-");
        mouthsMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouthsMinusActionPerformed(evt);
            }
        });

        otherBottomMinus.setText("-");
        otherBottomMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherBottomMinusActionPerformed(evt);
            }
        });

        otherTopMinus.setText("-");
        otherTopMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherTopMinusActionPerformed(evt);
            }
        });

        skinMinus.setText("-");
        skinMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skinMinusActionPerformed(evt);
            }
        });

        nosesMinus.setText("-");
        nosesMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosesMinusActionPerformed(evt);
            }
        });

        clothesPlus.setText("+");
        clothesPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesPlusActionPerformed(evt);
            }
        });

        eyebrowsPlus.setText("+");
        eyebrowsPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyebrowsPlusActionPerformed(evt);
            }
        });

        eyesPlus.setText("+");
        eyesPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyesPlusActionPerformed(evt);
            }
        });

        hairPlus.setText("+");
        hairPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairPlusActionPerformed(evt);
            }
        });

        hatsPlus.setText("+");
        hatsPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatsPlusActionPerformed(evt);
            }
        });

        mouthsPlus.setText("+");
        mouthsPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouthsPlusActionPerformed(evt);
            }
        });

        otherBottomPlus.setText("+");
        otherBottomPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherBottomPlusActionPerformed(evt);
            }
        });

        otherTopPlus.setText("+");
        otherTopPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherTopPlusActionPerformed(evt);
            }
        });

        skinPlus.setText("+");
        skinPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skinPlusActionPerformed(evt);
            }
        });

        nosesPlus.setText("+");
        nosesPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosesPlusActionPerformed(evt);
            }
        });

        clothesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clothesText.setText("Clothes: 0");

        eyebrowsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eyebrowsText.setText("Eyebrows: 0");

        eyesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eyesText.setText("Eyes: 0");

        hairText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hairText.setText("Hair: 0");

        hatsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hatsText.setText("Hat: 0");

        mouthsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mouthsText.setText("Mouth: 0");

        nosesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nosesText.setText("Nose: 0");

        otherBottomText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherBottomText.setText("Other A: 0");

        otherTopText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherTopText.setText("Other B: 0");

        skinText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skinText.setText("Skin: 0");

        hairColorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/colorpicker.png"))); // NOI18N
        hairColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairColorButtonActionPerformed(evt);
            }
        });

        eyebrowsColorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/colorpicker.png"))); // NOI18N
        eyebrowsColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyebrowsColorButtonActionPerformed(evt);
            }
        });

        clothesColorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/colorpicker.png"))); // NOI18N
        clothesColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hairColorButton)
                    .addComponent(eyebrowsColorButton)
                    .addComponent(clothesColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(clothesMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clothesText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(eyebrowsMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eyebrowsText, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(eyesMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eyesText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mouthsMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mouthsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nosesMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nosesText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(skinMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skinText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(otherBottomMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherBottomText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(otherTopMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherTopText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hatsMinus)
                            .addComponent(hairMinus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hairText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hatsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clothesPlus)
                    .addComponent(eyebrowsPlus)
                    .addComponent(eyesPlus)
                    .addComponent(hairPlus)
                    .addComponent(hatsPlus)
                    .addComponent(mouthsPlus)
                    .addComponent(otherBottomPlus)
                    .addComponent(skinPlus)
                    .addComponent(nosesPlus)
                    .addComponent(otherTopPlus))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clothesMinus)
                                .addComponent(clothesText))
                            .addComponent(clothesColorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eyebrowsMinus)
                            .addComponent(eyebrowsColorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eyesMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hairMinus)
                            .addComponent(hairColorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hatsMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mouthsMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nosesMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherBottomMinus)
                            .addComponent(otherBottomText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherTopMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(skinMinus))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(clothesPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eyebrowsPlus)
                            .addComponent(eyebrowsText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eyesPlus)
                            .addComponent(eyesText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hairPlus)
                            .addComponent(hairText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hatsPlus)
                            .addComponent(hatsText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mouthsPlus)
                            .addComponent(mouthsText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nosesPlus)
                            .addComponent(nosesText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherBottomPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherTopPlus)
                            .addComponent(otherTopText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(skinPlus)
                            .addComponent(skinText))))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        characterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/characters/2528.png"))); // NOI18N
        characterLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Identity"));

        jLabel2.setText("Name:");

        nameField.setText("Someone");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-Binary" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Gender:");

        jLabel12.setText("Favorite Color:");

        colorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet" }));

        jLabel13.setText("Birth Month:");

        birthMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel14.setText("Birth Day:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jSpinner1.setMaximumSize(new java.awt.Dimension(31, 31));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField)
                            .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthMonthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(colorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(birthMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Personality"));

        personalitySliderIE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                personalitySliderIEStateChanged(evt);
            }
        });

        jLabel4.setText("Introverted");

        jLabel5.setText("Extraverted");

        personalitySliderIS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                personalitySliderISStateChanged(evt);
            }
        });

        jLabel6.setText("Sensing");

        jLabel7.setText("Intuitive");

        personalitySliderFT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                personalitySliderFTStateChanged(evt);
            }
        });

        jLabel8.setText("Thinking");

        jLabel9.setText("Feeling");

        jLabel10.setText("Judging");

        personalitySliderPJ.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                personalitySliderPJStateChanged(evt);
            }
        });

        jLabel11.setText("Percieving");

        personalityLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        personalityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalityLabel.setText("INFP");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personalitySliderIE, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addComponent(personalitySliderIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(personalitySliderFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(personalitySliderPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personalityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(personalitySliderIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addComponent(personalitySliderIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(2, 2, 2)
                .addComponent(personalitySliderFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(2, 2, 2)
                .addComponent(personalitySliderPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(characterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            CharacterCreator.generateCharacter(true);
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateCharacter() throws IOException {
        CharacterCreator.generateCharacter(false);
        characterLabel.setIcon(new ImageIcon(CharacterCreator.getImage()));
    }

    private void clothesMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesMinusActionPerformed

        clothesText.setText("Clothes: " + CharacterCreator.cClothes.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clothesMinusActionPerformed

    private void eyebrowsMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyebrowsMinusActionPerformed

        eyebrowsText.setText("Eyebrows: " + CharacterCreator.cEyebrows.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eyebrowsMinusActionPerformed

    private void eyesMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyesMinusActionPerformed

        eyesText.setText("Eyes: " + CharacterCreator.cEyes.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eyesMinusActionPerformed

    private void hairMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairMinusActionPerformed

        hairText.setText("Hair: " + CharacterCreator.cHair.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hairMinusActionPerformed

    private void hatsMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatsMinusActionPerformed

        hatsText.setText("Hat: " + CharacterCreator.cHat.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hatsMinusActionPerformed

    private void mouthsMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouthsMinusActionPerformed

        mouthsText.setText("Mouth: " + CharacterCreator.cMouth.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mouthsMinusActionPerformed

    private void otherBottomMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherBottomMinusActionPerformed

        otherBottomText.setText("Other A: " + CharacterCreator.cOtherBottom.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_otherBottomMinusActionPerformed

    private void otherTopMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherTopMinusActionPerformed

        otherTopText.setText("Other B: " + CharacterCreator.cOtherTop.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_otherTopMinusActionPerformed

    private void skinMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skinMinusActionPerformed

        skinText.setText("Skin: " + CharacterCreator.cSkin.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_skinMinusActionPerformed

    private void nosesMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosesMinusActionPerformed

        nosesText.setText("Nose: " + CharacterCreator.cNose.decrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nosesMinusActionPerformed

    private void clothesPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesPlusActionPerformed

        clothesText.setText("Clothes: " + CharacterCreator.cClothes.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clothesPlusActionPerformed

    private void eyebrowsPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyebrowsPlusActionPerformed

        eyebrowsText.setText("Eyebrows: " + CharacterCreator.cEyebrows.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eyebrowsPlusActionPerformed

    private void eyesPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyesPlusActionPerformed

        eyesText.setText("Eyes: " + CharacterCreator.cEyes.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eyesPlusActionPerformed

    private void hairPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairPlusActionPerformed

        hairText.setText("Hair: " + CharacterCreator.cHair.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hairPlusActionPerformed

    private void hatsPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatsPlusActionPerformed

        hatsText.setText("Hat: " + CharacterCreator.cHat.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hatsPlusActionPerformed

    private void mouthsPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouthsPlusActionPerformed

        mouthsText.setText("Mouth: " + CharacterCreator.cMouth.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mouthsPlusActionPerformed

    private void otherBottomPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherBottomPlusActionPerformed

        otherBottomText.setText("Other A: " + CharacterCreator.cOtherBottom.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_otherBottomPlusActionPerformed

    private void otherTopPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherTopPlusActionPerformed

        otherTopText.setText("Other B: " + CharacterCreator.cOtherTop.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_otherTopPlusActionPerformed

    private void skinPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skinPlusActionPerformed

        skinText.setText("Skin: " + CharacterCreator.cSkin.incrementId());

        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_skinPlusActionPerformed

    private void nosesPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosesPlusActionPerformed

        nosesText.setText("Nose: " + CharacterCreator.cNose.incrementId());
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nosesPlusActionPerformed

    private void hairColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairColorButtonActionPerformed
        Color newColor = JColorChooser.showDialog(null, "Choose a color", Color.WHITE);
        CharacterCreator.cHair.setColor(newColor);
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hairColorButtonActionPerformed

    private void eyebrowsColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyebrowsColorButtonActionPerformed
        Color newColor = JColorChooser.showDialog(null, "Choose a color", Color.WHITE);
        CharacterCreator.cEyebrows.setColor(newColor);
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eyebrowsColorButtonActionPerformed

    private void clothesColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesColorButtonActionPerformed
                Color newColor = JColorChooser.showDialog(null, "Choose a color", Color.WHITE);
        CharacterCreator.cClothes.setColor(newColor);
        try {
            updateCharacter();
        } catch (IOException ex) {
            Logger.getLogger(CharacterCreatorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clothesColorButtonActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void personalitySliderIEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_personalitySliderIEStateChanged
        CharacterCreator.personalityEI = personalitySliderIE.getValue();
        updatePersonality();
    }//GEN-LAST:event_personalitySliderIEStateChanged

    private void personalitySliderISStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_personalitySliderISStateChanged
        CharacterCreator.personalityNS = personalitySliderIS.getValue();
        updatePersonality();
    }//GEN-LAST:event_personalitySliderISStateChanged

    private void personalitySliderFTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_personalitySliderFTStateChanged
        CharacterCreator.personalityFT = personalitySliderFT.getValue();
        updatePersonality();
    }//GEN-LAST:event_personalitySliderFTStateChanged

    private void personalitySliderPJStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_personalitySliderPJStateChanged
        CharacterCreator.personalityPJ = personalitySliderPJ.getValue();
        updatePersonality();
    }//GEN-LAST:event_personalitySliderPJStateChanged

    private void updatePersonality() {
        personalityLabel.setText(CharacterCreator.calculatePersonality());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> birthMonthComboBox;
    private javax.swing.JLabel characterLabel;
    private javax.swing.JButton clothesColorButton;
    private javax.swing.JButton clothesMinus;
    private javax.swing.JButton clothesPlus;
    private javax.swing.JLabel clothesText;
    private javax.swing.JComboBox<String> colorComboBox;
    private javax.swing.JButton eyebrowsColorButton;
    private javax.swing.JButton eyebrowsMinus;
    private javax.swing.JButton eyebrowsPlus;
    private javax.swing.JLabel eyebrowsText;
    private javax.swing.JButton eyesMinus;
    private javax.swing.JButton eyesPlus;
    private javax.swing.JLabel eyesText;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JButton hairColorButton;
    private javax.swing.JButton hairMinus;
    private javax.swing.JButton hairPlus;
    private javax.swing.JLabel hairText;
    private javax.swing.JButton hatsMinus;
    private javax.swing.JButton hatsPlus;
    private javax.swing.JLabel hatsText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton mouthsMinus;
    private javax.swing.JButton mouthsPlus;
    private javax.swing.JLabel mouthsText;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton nosesMinus;
    private javax.swing.JButton nosesPlus;
    private javax.swing.JLabel nosesText;
    private javax.swing.JButton otherBottomMinus;
    private javax.swing.JButton otherBottomPlus;
    private javax.swing.JLabel otherBottomText;
    private javax.swing.JButton otherTopMinus;
    private javax.swing.JButton otherTopPlus;
    private javax.swing.JLabel otherTopText;
    private javax.swing.JLabel personalityLabel;
    private javax.swing.JSlider personalitySliderFT;
    private javax.swing.JSlider personalitySliderIE;
    private javax.swing.JSlider personalitySliderIS;
    private javax.swing.JSlider personalitySliderPJ;
    private javax.swing.JButton skinMinus;
    private javax.swing.JButton skinPlus;
    private javax.swing.JLabel skinText;
    // End of variables declaration//GEN-END:variables
}
